#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
sed -i "s|log_folder = /tmp|log_folder = $OPENSHIFT_LOG_DIR|g" $OPENSHIFT_REPO_DIR/wsgi/silpa/silpa.conf
# Create static page links to here
ln -s $OPENSHIFT_REPO_DIR/wsgi/silpa/static/* $OPENSHIFT_REPO_DIR/wsgi/static
