from setuptools import setup

setup(name='YourAppName',
      version='1.0',
      description='OpenShift App',
      author='Your Name',
      author_email='example@example.com',
      url='http://www.python.org/sigs/distutils-sig/',
      install_requires=['Flask>=0.7.2',
                        'transliteration',
                        'spellchecker',
                        'hyphenation',
                        'inexactsearch',
                        'normalizer>=0.1',
			'silpa_common>=0.1',
                        'soundex',
                        'payyans',
                        'chardetails',
			'guesslanguage>=0.1'],
     )
