from setuptools import setup

setup(name='YourAppName',
      version='1.0',
      description='OpenShift App',
      author='Your Name',
      author_email='example@example.com',
      url='http://www.python.org/sigs/distutils-sig/',
      install_requires=['Flask',
                        'transliteration >= 0.4.1',
                        'spellchecker >= 0.4',
                        'hyphenation >= 2.0',
                        'inexactsearch >= 0.3',
                        'normalizer >= 0.2',
			'silpa_common >= 0.1.1',
                        'soundex >= 0.3.1',
                        'payyans >= 0.2',
                        'chardetails >= 0.3',
			'guesslanguage >= 0.2.1'],
     )
